// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base/types/gfspserver/download.proto

package gfspserver

import (
	context "context"
	fmt "fmt"
	gfsperrors "github.com/bnb-chain/greenfield-storage-provider/base/types/gfsperrors"
	gfsptask "github.com/bnb-chain/greenfield-storage-provider/base/types/gfsptask"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GfSpDownloadObjectRequest struct {
	DownLoadTask *gfsptask.GfSpDownloadObjectTask `protobuf:"bytes,1,opt,name=down_load_task,json=downLoadTask,proto3" json:"down_load_task,omitempty"`
}

func (m *GfSpDownloadObjectRequest) Reset()         { *m = GfSpDownloadObjectRequest{} }
func (m *GfSpDownloadObjectRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpDownloadObjectRequest) ProtoMessage()    {}
func (*GfSpDownloadObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9c5d8fc8df4b20, []int{0}
}
func (m *GfSpDownloadObjectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpDownloadObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpDownloadObjectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpDownloadObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpDownloadObjectRequest.Merge(m, src)
}
func (m *GfSpDownloadObjectRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpDownloadObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpDownloadObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpDownloadObjectRequest proto.InternalMessageInfo

func (m *GfSpDownloadObjectRequest) GetDownLoadTask() *gfsptask.GfSpDownloadObjectTask {
	if m != nil {
		return m.DownLoadTask
	}
	return nil
}

type GfSpDownloadObjectResponse struct {
	Err  *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data []byte                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *GfSpDownloadObjectResponse) Reset()         { *m = GfSpDownloadObjectResponse{} }
func (m *GfSpDownloadObjectResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpDownloadObjectResponse) ProtoMessage()    {}
func (*GfSpDownloadObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9c5d8fc8df4b20, []int{1}
}
func (m *GfSpDownloadObjectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpDownloadObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpDownloadObjectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpDownloadObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpDownloadObjectResponse.Merge(m, src)
}
func (m *GfSpDownloadObjectResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpDownloadObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpDownloadObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpDownloadObjectResponse proto.InternalMessageInfo

func (m *GfSpDownloadObjectResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GfSpDownloadObjectResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GfSpGetChallengeInfoRequest struct {
	ChallengePieceTask *gfsptask.GfSpChallengePieceTask `protobuf:"bytes,1,opt,name=challenge_piece_task,json=challengePieceTask,proto3" json:"challenge_piece_task,omitempty"`
}

func (m *GfSpGetChallengeInfoRequest) Reset()         { *m = GfSpGetChallengeInfoRequest{} }
func (m *GfSpGetChallengeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpGetChallengeInfoRequest) ProtoMessage()    {}
func (*GfSpGetChallengeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9c5d8fc8df4b20, []int{2}
}
func (m *GfSpGetChallengeInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpGetChallengeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpGetChallengeInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpGetChallengeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpGetChallengeInfoRequest.Merge(m, src)
}
func (m *GfSpGetChallengeInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpGetChallengeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpGetChallengeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpGetChallengeInfoRequest proto.InternalMessageInfo

func (m *GfSpGetChallengeInfoRequest) GetChallengePieceTask() *gfsptask.GfSpChallengePieceTask {
	if m != nil {
		return m.ChallengePieceTask
	}
	return nil
}

type GfSpGetChallengeInfoResponse struct {
	Err           *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          []byte                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IntegrityHash []byte                `protobuf:"bytes,3,opt,name=integrity_hash,json=integrityHash,proto3" json:"integrity_hash,omitempty"`
	Checksums     [][]byte              `protobuf:"bytes,4,rep,name=checksums,proto3" json:"checksums,omitempty"`
}

func (m *GfSpGetChallengeInfoResponse) Reset()         { *m = GfSpGetChallengeInfoResponse{} }
func (m *GfSpGetChallengeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpGetChallengeInfoResponse) ProtoMessage()    {}
func (*GfSpGetChallengeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e9c5d8fc8df4b20, []int{3}
}
func (m *GfSpGetChallengeInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpGetChallengeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpGetChallengeInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpGetChallengeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpGetChallengeInfoResponse.Merge(m, src)
}
func (m *GfSpGetChallengeInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpGetChallengeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpGetChallengeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpGetChallengeInfoResponse proto.InternalMessageInfo

func (m *GfSpGetChallengeInfoResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GfSpGetChallengeInfoResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GfSpGetChallengeInfoResponse) GetIntegrityHash() []byte {
	if m != nil {
		return m.IntegrityHash
	}
	return nil
}

func (m *GfSpGetChallengeInfoResponse) GetChecksums() [][]byte {
	if m != nil {
		return m.Checksums
	}
	return nil
}

func init() {
	proto.RegisterType((*GfSpDownloadObjectRequest)(nil), "base.types.gfspserver.GfSpDownloadObjectRequest")
	proto.RegisterType((*GfSpDownloadObjectResponse)(nil), "base.types.gfspserver.GfSpDownloadObjectResponse")
	proto.RegisterType((*GfSpGetChallengeInfoRequest)(nil), "base.types.gfspserver.GfSpGetChallengeInfoRequest")
	proto.RegisterType((*GfSpGetChallengeInfoResponse)(nil), "base.types.gfspserver.GfSpGetChallengeInfoResponse")
}

func init() {
	proto.RegisterFile("base/types/gfspserver/download.proto", fileDescriptor_4e9c5d8fc8df4b20)
}

var fileDescriptor_4e9c5d8fc8df4b20 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xae, 0xd7, 0x09, 0x09, 0x53, 0x76, 0x61, 0x86, 0x54, 0xc2, 0x14, 0x95, 0x08, 0xa4, 0x4a,
	0xa8, 0x31, 0x74, 0x6f, 0xc0, 0xdf, 0x40, 0x42, 0x02, 0x32, 0xae, 0x90, 0x50, 0x71, 0x9c, 0xd3,
	0xc4, 0xb4, 0xb3, 0x83, 0xed, 0x16, 0x4d, 0x70, 0xc3, 0x1b, 0x70, 0xc5, 0x4b, 0xf0, 0x22, 0x5c,
	0xee, 0x92, 0x4b, 0xd4, 0xbe, 0x08, 0xb2, 0xb3, 0x6e, 0x28, 0xcd, 0x10, 0x95, 0xb8, 0x49, 0xec,
	0x73, 0xbe, 0xef, 0x7c, 0xe7, 0xf3, 0xb1, 0xf1, 0xed, 0x94, 0x19, 0xa0, 0xf6, 0xb8, 0x04, 0x43,
	0xf3, 0xb1, 0x29, 0x0d, 0xe8, 0x39, 0x68, 0x9a, 0xa9, 0x8f, 0x72, 0xaa, 0x58, 0x16, 0x97, 0x5a,
	0x59, 0x45, 0xae, 0x3b, 0x54, 0xec, 0x51, 0xf1, 0x39, 0x2a, 0xb8, 0x55, 0x23, 0x83, 0xd6, 0x4a,
	0x1b, 0xea, 0x7f, 0x15, 0x33, 0x08, 0x6b, 0x10, 0xcb, 0xcc, 0x84, 0xba, 0x4f, 0x95, 0x8f, 0x24,
	0xbe, 0x71, 0x30, 0x3e, 0x2c, 0x1f, 0x9d, 0xea, 0xbd, 0x48, 0xdf, 0x03, 0xb7, 0x09, 0x7c, 0x98,
	0x81, 0xb1, 0xe4, 0x15, 0xde, 0x71, 0x8d, 0x8c, 0x5c, 0x66, 0xe4, 0x48, 0x5d, 0xd4, 0x43, 0xfd,
	0x2b, 0xc3, 0xbb, 0x71, 0xad, 0x1f, 0x5f, 0x70, 0xbd, 0xce, 0x6b, 0x66, 0x26, 0x49, 0xc7, 0x95,
	0x78, 0xae, 0x58, 0xe6, 0x76, 0x51, 0x86, 0x83, 0x26, 0x3d, 0x53, 0x2a, 0x69, 0x80, 0x0c, 0x71,
	0x1b, 0xb4, 0x3e, 0x55, 0xe9, 0xd5, 0x55, 0x2a, 0x7b, 0x5e, 0xe7, 0xb1, 0x5b, 0x26, 0x0e, 0x4c,
	0x08, 0xde, 0xce, 0x98, 0x65, 0xdd, 0xad, 0x1e, 0xea, 0x77, 0x12, 0xbf, 0x8e, 0x3e, 0xe3, 0x9b,
	0x0e, 0x75, 0x00, 0xf6, 0x61, 0xc1, 0xa6, 0x53, 0x90, 0x39, 0x3c, 0x93, 0x63, 0xb5, 0xf2, 0xf5,
	0x16, 0xef, 0xf2, 0x55, 0x7c, 0x54, 0x0a, 0xe0, 0xf0, 0x6f, 0xee, 0xce, 0x8a, 0xbd, 0x74, 0x1c,
	0xef, 0x8e, 0xf0, 0xb5, 0x58, 0xf4, 0x1d, 0xe1, 0xbd, 0x66, 0xf9, 0xff, 0x6b, 0x93, 0xdc, 0xc1,
	0x3b, 0x42, 0x5a, 0xc8, 0xb5, 0xb0, 0xc7, 0xa3, 0x82, 0x99, 0xa2, 0xdb, 0xf6, 0xd9, 0xab, 0x67,
	0xd1, 0xa7, 0xcc, 0x14, 0x64, 0x0f, 0x5f, 0xe6, 0x05, 0xf0, 0x89, 0x99, 0x1d, 0x99, 0xee, 0x76,
	0xaf, 0xdd, 0xef, 0x24, 0xe7, 0x81, 0xe1, 0xb7, 0x2d, 0x7c, 0xed, 0xcf, 0x91, 0x1c, 0x82, 0x9e,
	0x0b, 0x0e, 0xe4, 0x13, 0x26, 0xeb, 0x93, 0x22, 0xf7, 0xe2, 0xc6, 0xab, 0x18, 0x5f, 0x78, 0x89,
	0x82, 0xfb, 0x1b, 0x30, 0xaa, 0xf3, 0x89, 0x5a, 0xe4, 0x0b, 0xc2, 0xbb, 0x4d, 0x47, 0x48, 0x86,
	0x7f, 0xa9, 0x76, 0xc1, 0xb8, 0x83, 0xfd, 0x8d, 0x38, 0xab, 0x1e, 0x1e, 0xbc, 0xfb, 0xb1, 0x08,
	0xd1, 0xc9, 0x22, 0x44, 0xbf, 0x16, 0x21, 0xfa, 0xba, 0x0c, 0x5b, 0x27, 0xcb, 0xb0, 0xf5, 0x73,
	0x19, 0xb6, 0xde, 0x3c, 0xc9, 0x85, 0x2d, 0x66, 0x69, 0xcc, 0xd5, 0x11, 0x4d, 0x65, 0x3a, 0xe0,
	0x05, 0x13, 0x92, 0xe6, 0x1a, 0x40, 0x8e, 0x05, 0x4c, 0xb3, 0x81, 0xb1, 0x4a, 0xb3, 0x1c, 0x06,
	0xa5, 0x56, 0x73, 0x91, 0x81, 0xa6, 0x8d, 0xaf, 0x3c, 0xbd, 0xe4, 0xdf, 0xe0, 0xfe, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x03, 0x92, 0x24, 0xb2, 0x05, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GfSpDownloadServiceClient is the client API for GfSpDownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GfSpDownloadServiceClient interface {
	GfSpDownloadObject(ctx context.Context, in *GfSpDownloadObjectRequest, opts ...grpc.CallOption) (*GfSpDownloadObjectResponse, error)
	GfSpGetChallengeInfo(ctx context.Context, in *GfSpGetChallengeInfoRequest, opts ...grpc.CallOption) (*GfSpGetChallengeInfoResponse, error)
}

type gfSpDownloadServiceClient struct {
	cc grpc1.ClientConn
}

func NewGfSpDownloadServiceClient(cc grpc1.ClientConn) GfSpDownloadServiceClient {
	return &gfSpDownloadServiceClient{cc}
}

func (c *gfSpDownloadServiceClient) GfSpDownloadObject(ctx context.Context, in *GfSpDownloadObjectRequest, opts ...grpc.CallOption) (*GfSpDownloadObjectResponse, error) {
	out := new(GfSpDownloadObjectResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpDownloadService/GfSpDownloadObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gfSpDownloadServiceClient) GfSpGetChallengeInfo(ctx context.Context, in *GfSpGetChallengeInfoRequest, opts ...grpc.CallOption) (*GfSpGetChallengeInfoResponse, error) {
	out := new(GfSpGetChallengeInfoResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpDownloadService/GfSpGetChallengeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GfSpDownloadServiceServer is the server API for GfSpDownloadService service.
type GfSpDownloadServiceServer interface {
	GfSpDownloadObject(context.Context, *GfSpDownloadObjectRequest) (*GfSpDownloadObjectResponse, error)
	GfSpGetChallengeInfo(context.Context, *GfSpGetChallengeInfoRequest) (*GfSpGetChallengeInfoResponse, error)
}

// UnimplementedGfSpDownloadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGfSpDownloadServiceServer struct {
}

func (*UnimplementedGfSpDownloadServiceServer) GfSpDownloadObject(ctx context.Context, req *GfSpDownloadObjectRequest) (*GfSpDownloadObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpDownloadObject not implemented")
}
func (*UnimplementedGfSpDownloadServiceServer) GfSpGetChallengeInfo(ctx context.Context, req *GfSpGetChallengeInfoRequest) (*GfSpGetChallengeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpGetChallengeInfo not implemented")
}

func RegisterGfSpDownloadServiceServer(s grpc1.Server, srv GfSpDownloadServiceServer) {
	s.RegisterService(&_GfSpDownloadService_serviceDesc, srv)
}

func _GfSpDownloadService_GfSpDownloadObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpDownloadObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpDownloadServiceServer).GfSpDownloadObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpDownloadService/GfSpDownloadObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpDownloadServiceServer).GfSpDownloadObject(ctx, req.(*GfSpDownloadObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GfSpDownloadService_GfSpGetChallengeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpGetChallengeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpDownloadServiceServer).GfSpGetChallengeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpDownloadService/GfSpGetChallengeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpDownloadServiceServer).GfSpGetChallengeInfo(ctx, req.(*GfSpGetChallengeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GfSpDownloadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.types.gfspserver.GfSpDownloadService",
	HandlerType: (*GfSpDownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GfSpDownloadObject",
			Handler:    _GfSpDownloadService_GfSpDownloadObject_Handler,
		},
		{
			MethodName: "GfSpGetChallengeInfo",
			Handler:    _GfSpDownloadService_GfSpGetChallengeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/types/gfspserver/download.proto",
}

func (m *GfSpDownloadObjectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpDownloadObjectRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpDownloadObjectRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DownLoadTask != nil {
		{
			size, err := m.DownLoadTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDownload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpDownloadObjectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpDownloadObjectResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpDownloadObjectResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintDownload(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDownload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpGetChallengeInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpGetChallengeInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpGetChallengeInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChallengePieceTask != nil {
		{
			size, err := m.ChallengePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDownload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpGetChallengeInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpGetChallengeInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpGetChallengeInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Checksums) > 0 {
		for iNdEx := len(m.Checksums) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Checksums[iNdEx])
			copy(dAtA[i:], m.Checksums[iNdEx])
			i = encodeVarintDownload(dAtA, i, uint64(len(m.Checksums[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.IntegrityHash) > 0 {
		i -= len(m.IntegrityHash)
		copy(dAtA[i:], m.IntegrityHash)
		i = encodeVarintDownload(dAtA, i, uint64(len(m.IntegrityHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintDownload(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDownload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDownload(dAtA []byte, offset int, v uint64) int {
	offset -= sovDownload(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GfSpDownloadObjectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownLoadTask != nil {
		l = m.DownLoadTask.Size()
		n += 1 + l + sovDownload(uint64(l))
	}
	return n
}

func (m *GfSpDownloadObjectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovDownload(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovDownload(uint64(l))
	}
	return n
}

func (m *GfSpGetChallengeInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengePieceTask != nil {
		l = m.ChallengePieceTask.Size()
		n += 1 + l + sovDownload(uint64(l))
	}
	return n
}

func (m *GfSpGetChallengeInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovDownload(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovDownload(uint64(l))
	}
	l = len(m.IntegrityHash)
	if l > 0 {
		n += 1 + l + sovDownload(uint64(l))
	}
	if len(m.Checksums) > 0 {
		for _, b := range m.Checksums {
			l = len(b)
			n += 1 + l + sovDownload(uint64(l))
		}
	}
	return n
}

func sovDownload(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDownload(x uint64) (n int) {
	return sovDownload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GfSpDownloadObjectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDownload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpDownloadObjectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpDownloadObjectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownLoadTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DownLoadTask == nil {
				m.DownLoadTask = &gfsptask.GfSpDownloadObjectTask{}
			}
			if err := m.DownLoadTask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDownload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDownload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpDownloadObjectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDownload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpDownloadObjectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpDownloadObjectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDownload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDownload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpGetChallengeInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDownload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpGetChallengeInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpGetChallengeInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChallengePieceTask == nil {
				m.ChallengePieceTask = &gfsptask.GfSpChallengePieceTask{}
			}
			if err := m.ChallengePieceTask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDownload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDownload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpGetChallengeInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDownload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpGetChallengeInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpGetChallengeInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntegrityHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IntegrityHash = append(m.IntegrityHash[:0], dAtA[iNdEx:postIndex]...)
			if m.IntegrityHash == nil {
				m.IntegrityHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksums", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDownload
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDownload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksums = append(m.Checksums, make([]byte, postIndex-iNdEx))
			copy(m.Checksums[len(m.Checksums)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDownload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDownload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDownload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDownload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDownload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDownload
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDownload
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDownload
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDownload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDownload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDownload = fmt.Errorf("proto: unexpected end of group")
)
