// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base/types/gfspserver/manage.proto

package gfspserver

import (
	context "context"
	fmt "fmt"
	gfsperrors "github.com/bnb-chain/greenfield-storage-provider/base/types/gfsperrors"
	gfsplimit "github.com/bnb-chain/greenfield-storage-provider/base/types/gfsplimit"
	gfsptask "github.com/bnb-chain/greenfield-storage-provider/base/types/gfsptask"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GfSpBeginTaskRequest struct {
	// Types that are valid to be assigned to Request:
	//	*GfSpBeginTaskRequest_UploadObjectTask
	Request isGfSpBeginTaskRequest_Request `protobuf_oneof:"request"`
}

func (m *GfSpBeginTaskRequest) Reset()         { *m = GfSpBeginTaskRequest{} }
func (m *GfSpBeginTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpBeginTaskRequest) ProtoMessage()    {}
func (*GfSpBeginTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{0}
}
func (m *GfSpBeginTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpBeginTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpBeginTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpBeginTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpBeginTaskRequest.Merge(m, src)
}
func (m *GfSpBeginTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpBeginTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpBeginTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpBeginTaskRequest proto.InternalMessageInfo

type isGfSpBeginTaskRequest_Request interface {
	isGfSpBeginTaskRequest_Request()
	MarshalTo([]byte) (int, error)
	Size() int
}

type GfSpBeginTaskRequest_UploadObjectTask struct {
	UploadObjectTask *gfsptask.GfSpUploadObjectTask `protobuf:"bytes,1,opt,name=upload_object_task,json=uploadObjectTask,proto3,oneof" json:"upload_object_task,omitempty"`
}

func (*GfSpBeginTaskRequest_UploadObjectTask) isGfSpBeginTaskRequest_Request() {}

func (m *GfSpBeginTaskRequest) GetRequest() isGfSpBeginTaskRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *GfSpBeginTaskRequest) GetUploadObjectTask() *gfsptask.GfSpUploadObjectTask {
	if x, ok := m.GetRequest().(*GfSpBeginTaskRequest_UploadObjectTask); ok {
		return x.UploadObjectTask
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GfSpBeginTaskRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GfSpBeginTaskRequest_UploadObjectTask)(nil),
	}
}

type GfSpBeginTaskResponse struct {
	Err *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (m *GfSpBeginTaskResponse) Reset()         { *m = GfSpBeginTaskResponse{} }
func (m *GfSpBeginTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpBeginTaskResponse) ProtoMessage()    {}
func (*GfSpBeginTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{1}
}
func (m *GfSpBeginTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpBeginTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpBeginTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpBeginTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpBeginTaskResponse.Merge(m, src)
}
func (m *GfSpBeginTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpBeginTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpBeginTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpBeginTaskResponse proto.InternalMessageInfo

func (m *GfSpBeginTaskResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

type GfSpAskTaskRequest struct {
	NodeLimit *gfsplimit.GfSpLimit `protobuf:"bytes,1,opt,name=node_limit,json=nodeLimit,proto3" json:"node_limit,omitempty"`
}

func (m *GfSpAskTaskRequest) Reset()         { *m = GfSpAskTaskRequest{} }
func (m *GfSpAskTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpAskTaskRequest) ProtoMessage()    {}
func (*GfSpAskTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{2}
}
func (m *GfSpAskTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpAskTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpAskTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpAskTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpAskTaskRequest.Merge(m, src)
}
func (m *GfSpAskTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpAskTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpAskTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpAskTaskRequest proto.InternalMessageInfo

func (m *GfSpAskTaskRequest) GetNodeLimit() *gfsplimit.GfSpLimit {
	if m != nil {
		return m.NodeLimit
	}
	return nil
}

type GfSpAskTaskResponse struct {
	Err *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*GfSpAskTaskResponse_ReplicatePieceTask
	//	*GfSpAskTaskResponse_SealObjectTask
	//	*GfSpAskTaskResponse_ReceivePieceTask
	//	*GfSpAskTaskResponse_GcObjectTask
	//	*GfSpAskTaskResponse_GcZombiePieceTask
	//	*GfSpAskTaskResponse_GcMetaTask
	Response isGfSpAskTaskResponse_Response `protobuf_oneof:"response"`
}

func (m *GfSpAskTaskResponse) Reset()         { *m = GfSpAskTaskResponse{} }
func (m *GfSpAskTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpAskTaskResponse) ProtoMessage()    {}
func (*GfSpAskTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{3}
}
func (m *GfSpAskTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpAskTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpAskTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpAskTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpAskTaskResponse.Merge(m, src)
}
func (m *GfSpAskTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpAskTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpAskTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpAskTaskResponse proto.InternalMessageInfo

type isGfSpAskTaskResponse_Response interface {
	isGfSpAskTaskResponse_Response()
	MarshalTo([]byte) (int, error)
	Size() int
}

type GfSpAskTaskResponse_ReplicatePieceTask struct {
	ReplicatePieceTask *gfsptask.GfSpReplicatePieceTask `protobuf:"bytes,2,opt,name=replicate_piece_task,json=replicatePieceTask,proto3,oneof" json:"replicate_piece_task,omitempty"`
}
type GfSpAskTaskResponse_SealObjectTask struct {
	SealObjectTask *gfsptask.GfSpSealObjectTask `protobuf:"bytes,3,opt,name=seal_object_task,json=sealObjectTask,proto3,oneof" json:"seal_object_task,omitempty"`
}
type GfSpAskTaskResponse_ReceivePieceTask struct {
	ReceivePieceTask *gfsptask.GfSpReceivePieceTask `protobuf:"bytes,4,opt,name=receive_piece_task,json=receivePieceTask,proto3,oneof" json:"receive_piece_task,omitempty"`
}
type GfSpAskTaskResponse_GcObjectTask struct {
	GcObjectTask *gfsptask.GfSpGCObjectTask `protobuf:"bytes,5,opt,name=gc_object_task,json=gcObjectTask,proto3,oneof" json:"gc_object_task,omitempty"`
}
type GfSpAskTaskResponse_GcZombiePieceTask struct {
	GcZombiePieceTask *gfsptask.GfSpGCZombiePieceTask `protobuf:"bytes,6,opt,name=gc_zombie_piece_task,json=gcZombiePieceTask,proto3,oneof" json:"gc_zombie_piece_task,omitempty"`
}
type GfSpAskTaskResponse_GcMetaTask struct {
	GcMetaTask *gfsptask.GfSpGCMetaTask `protobuf:"bytes,7,opt,name=gc_meta_task,json=gcMetaTask,proto3,oneof" json:"gc_meta_task,omitempty"`
}

func (*GfSpAskTaskResponse_ReplicatePieceTask) isGfSpAskTaskResponse_Response() {}
func (*GfSpAskTaskResponse_SealObjectTask) isGfSpAskTaskResponse_Response()     {}
func (*GfSpAskTaskResponse_ReceivePieceTask) isGfSpAskTaskResponse_Response()   {}
func (*GfSpAskTaskResponse_GcObjectTask) isGfSpAskTaskResponse_Response()       {}
func (*GfSpAskTaskResponse_GcZombiePieceTask) isGfSpAskTaskResponse_Response()  {}
func (*GfSpAskTaskResponse_GcMetaTask) isGfSpAskTaskResponse_Response()         {}

func (m *GfSpAskTaskResponse) GetResponse() isGfSpAskTaskResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetReplicatePieceTask() *gfsptask.GfSpReplicatePieceTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_ReplicatePieceTask); ok {
		return x.ReplicatePieceTask
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetSealObjectTask() *gfsptask.GfSpSealObjectTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_SealObjectTask); ok {
		return x.SealObjectTask
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetReceivePieceTask() *gfsptask.GfSpReceivePieceTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_ReceivePieceTask); ok {
		return x.ReceivePieceTask
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetGcObjectTask() *gfsptask.GfSpGCObjectTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_GcObjectTask); ok {
		return x.GcObjectTask
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetGcZombiePieceTask() *gfsptask.GfSpGCZombiePieceTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_GcZombiePieceTask); ok {
		return x.GcZombiePieceTask
	}
	return nil
}

func (m *GfSpAskTaskResponse) GetGcMetaTask() *gfsptask.GfSpGCMetaTask {
	if x, ok := m.GetResponse().(*GfSpAskTaskResponse_GcMetaTask); ok {
		return x.GcMetaTask
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GfSpAskTaskResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GfSpAskTaskResponse_ReplicatePieceTask)(nil),
		(*GfSpAskTaskResponse_SealObjectTask)(nil),
		(*GfSpAskTaskResponse_ReceivePieceTask)(nil),
		(*GfSpAskTaskResponse_GcObjectTask)(nil),
		(*GfSpAskTaskResponse_GcZombiePieceTask)(nil),
		(*GfSpAskTaskResponse_GcMetaTask)(nil),
	}
}

type GfSpReportTaskRequest struct {
	// Types that are valid to be assigned to Request:
	//	*GfSpReportTaskRequest_UploadObjectTask
	//	*GfSpReportTaskRequest_ReplicatePieceTask
	//	*GfSpReportTaskRequest_SealObjectTask
	//	*GfSpReportTaskRequest_GcObjectTask
	//	*GfSpReportTaskRequest_GcZombiePieceTask
	//	*GfSpReportTaskRequest_GcMetaTask
	//	*GfSpReportTaskRequest_DownloadObjectTask
	//	*GfSpReportTaskRequest_ChallengePieceTask
	//	*GfSpReportTaskRequest_ReceivePieceTask
	Request isGfSpReportTaskRequest_Request `protobuf_oneof:"request"`
}

func (m *GfSpReportTaskRequest) Reset()         { *m = GfSpReportTaskRequest{} }
func (m *GfSpReportTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GfSpReportTaskRequest) ProtoMessage()    {}
func (*GfSpReportTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{4}
}
func (m *GfSpReportTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpReportTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpReportTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpReportTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpReportTaskRequest.Merge(m, src)
}
func (m *GfSpReportTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *GfSpReportTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpReportTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpReportTaskRequest proto.InternalMessageInfo

type isGfSpReportTaskRequest_Request interface {
	isGfSpReportTaskRequest_Request()
	MarshalTo([]byte) (int, error)
	Size() int
}

type GfSpReportTaskRequest_UploadObjectTask struct {
	UploadObjectTask *gfsptask.GfSpUploadObjectTask `protobuf:"bytes,1,opt,name=upload_object_task,json=uploadObjectTask,proto3,oneof" json:"upload_object_task,omitempty"`
}
type GfSpReportTaskRequest_ReplicatePieceTask struct {
	ReplicatePieceTask *gfsptask.GfSpReplicatePieceTask `protobuf:"bytes,2,opt,name=replicate_piece_task,json=replicatePieceTask,proto3,oneof" json:"replicate_piece_task,omitempty"`
}
type GfSpReportTaskRequest_SealObjectTask struct {
	SealObjectTask *gfsptask.GfSpSealObjectTask `protobuf:"bytes,3,opt,name=seal_object_task,json=sealObjectTask,proto3,oneof" json:"seal_object_task,omitempty"`
}
type GfSpReportTaskRequest_GcObjectTask struct {
	GcObjectTask *gfsptask.GfSpGCObjectTask `protobuf:"bytes,4,opt,name=gc_object_task,json=gcObjectTask,proto3,oneof" json:"gc_object_task,omitempty"`
}
type GfSpReportTaskRequest_GcZombiePieceTask struct {
	GcZombiePieceTask *gfsptask.GfSpGCZombiePieceTask `protobuf:"bytes,5,opt,name=gc_zombie_piece_task,json=gcZombiePieceTask,proto3,oneof" json:"gc_zombie_piece_task,omitempty"`
}
type GfSpReportTaskRequest_GcMetaTask struct {
	GcMetaTask *gfsptask.GfSpGCMetaTask `protobuf:"bytes,6,opt,name=gc_meta_task,json=gcMetaTask,proto3,oneof" json:"gc_meta_task,omitempty"`
}
type GfSpReportTaskRequest_DownloadObjectTask struct {
	DownloadObjectTask *gfsptask.GfSpDownloadObjectTask `protobuf:"bytes,7,opt,name=download_object_task,json=downloadObjectTask,proto3,oneof" json:"download_object_task,omitempty"`
}
type GfSpReportTaskRequest_ChallengePieceTask struct {
	ChallengePieceTask *gfsptask.GfSpChallengePieceTask `protobuf:"bytes,8,opt,name=challenge_piece_task,json=challengePieceTask,proto3,oneof" json:"challenge_piece_task,omitempty"`
}
type GfSpReportTaskRequest_ReceivePieceTask struct {
	ReceivePieceTask *gfsptask.GfSpReceivePieceTask `protobuf:"bytes,9,opt,name=receive_piece_task,json=receivePieceTask,proto3,oneof" json:"receive_piece_task,omitempty"`
}

func (*GfSpReportTaskRequest_UploadObjectTask) isGfSpReportTaskRequest_Request()   {}
func (*GfSpReportTaskRequest_ReplicatePieceTask) isGfSpReportTaskRequest_Request() {}
func (*GfSpReportTaskRequest_SealObjectTask) isGfSpReportTaskRequest_Request()     {}
func (*GfSpReportTaskRequest_GcObjectTask) isGfSpReportTaskRequest_Request()       {}
func (*GfSpReportTaskRequest_GcZombiePieceTask) isGfSpReportTaskRequest_Request()  {}
func (*GfSpReportTaskRequest_GcMetaTask) isGfSpReportTaskRequest_Request()         {}
func (*GfSpReportTaskRequest_DownloadObjectTask) isGfSpReportTaskRequest_Request() {}
func (*GfSpReportTaskRequest_ChallengePieceTask) isGfSpReportTaskRequest_Request() {}
func (*GfSpReportTaskRequest_ReceivePieceTask) isGfSpReportTaskRequest_Request()   {}

func (m *GfSpReportTaskRequest) GetRequest() isGfSpReportTaskRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetUploadObjectTask() *gfsptask.GfSpUploadObjectTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_UploadObjectTask); ok {
		return x.UploadObjectTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetReplicatePieceTask() *gfsptask.GfSpReplicatePieceTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_ReplicatePieceTask); ok {
		return x.ReplicatePieceTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetSealObjectTask() *gfsptask.GfSpSealObjectTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_SealObjectTask); ok {
		return x.SealObjectTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetGcObjectTask() *gfsptask.GfSpGCObjectTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_GcObjectTask); ok {
		return x.GcObjectTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetGcZombiePieceTask() *gfsptask.GfSpGCZombiePieceTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_GcZombiePieceTask); ok {
		return x.GcZombiePieceTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetGcMetaTask() *gfsptask.GfSpGCMetaTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_GcMetaTask); ok {
		return x.GcMetaTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetDownloadObjectTask() *gfsptask.GfSpDownloadObjectTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_DownloadObjectTask); ok {
		return x.DownloadObjectTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetChallengePieceTask() *gfsptask.GfSpChallengePieceTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_ChallengePieceTask); ok {
		return x.ChallengePieceTask
	}
	return nil
}

func (m *GfSpReportTaskRequest) GetReceivePieceTask() *gfsptask.GfSpReceivePieceTask {
	if x, ok := m.GetRequest().(*GfSpReportTaskRequest_ReceivePieceTask); ok {
		return x.ReceivePieceTask
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GfSpReportTaskRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GfSpReportTaskRequest_UploadObjectTask)(nil),
		(*GfSpReportTaskRequest_ReplicatePieceTask)(nil),
		(*GfSpReportTaskRequest_SealObjectTask)(nil),
		(*GfSpReportTaskRequest_GcObjectTask)(nil),
		(*GfSpReportTaskRequest_GcZombiePieceTask)(nil),
		(*GfSpReportTaskRequest_GcMetaTask)(nil),
		(*GfSpReportTaskRequest_DownloadObjectTask)(nil),
		(*GfSpReportTaskRequest_ChallengePieceTask)(nil),
		(*GfSpReportTaskRequest_ReceivePieceTask)(nil),
	}
}

type GfSpReportTaskResponse struct {
	Err *gfsperrors.GfSpError `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (m *GfSpReportTaskResponse) Reset()         { *m = GfSpReportTaskResponse{} }
func (m *GfSpReportTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GfSpReportTaskResponse) ProtoMessage()    {}
func (*GfSpReportTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7801aa704e62bc53, []int{5}
}
func (m *GfSpReportTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GfSpReportTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GfSpReportTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GfSpReportTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GfSpReportTaskResponse.Merge(m, src)
}
func (m *GfSpReportTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *GfSpReportTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GfSpReportTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GfSpReportTaskResponse proto.InternalMessageInfo

func (m *GfSpReportTaskResponse) GetErr() *gfsperrors.GfSpError {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*GfSpBeginTaskRequest)(nil), "base.types.gfspserver.GfSpBeginTaskRequest")
	proto.RegisterType((*GfSpBeginTaskResponse)(nil), "base.types.gfspserver.GfSpBeginTaskResponse")
	proto.RegisterType((*GfSpAskTaskRequest)(nil), "base.types.gfspserver.GfSpAskTaskRequest")
	proto.RegisterType((*GfSpAskTaskResponse)(nil), "base.types.gfspserver.GfSpAskTaskResponse")
	proto.RegisterType((*GfSpReportTaskRequest)(nil), "base.types.gfspserver.GfSpReportTaskRequest")
	proto.RegisterType((*GfSpReportTaskResponse)(nil), "base.types.gfspserver.GfSpReportTaskResponse")
}

func init() {
	proto.RegisterFile("base/types/gfspserver/manage.proto", fileDescriptor_7801aa704e62bc53)
}

var fileDescriptor_7801aa704e62bc53 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x5f, 0x4f, 0x13, 0x4f,
	0x14, 0x6d, 0xf9, 0x53, 0x60, 0xe0, 0x47, 0x60, 0x7e, 0x60, 0x4c, 0x1f, 0x56, 0xac, 0x31, 0x0a,
	0xda, 0x6e, 0x82, 0xef, 0x26, 0x16, 0x15, 0x13, 0x21, 0x9a, 0x2d, 0x3e, 0x48, 0x62, 0xd6, 0xd9,
	0xe9, 0xed, 0xb0, 0xb2, 0xdd, 0x59, 0x67, 0xa6, 0x35, 0x1a, 0x3f, 0x84, 0xdf, 0x4a, 0x1f, 0x79,
	0x34, 0x26, 0x26, 0x06, 0xbe, 0x88, 0x99, 0xd9, 0xad, 0x76, 0x76, 0x69, 0x21, 0x44, 0x4c, 0x7c,
	0xd9, 0x4e, 0x6f, 0xef, 0x39, 0xf7, 0xf6, 0xcc, 0x99, 0xb9, 0x8b, 0x6a, 0x01, 0x91, 0xe0, 0xaa,
	0xf7, 0x09, 0x48, 0x97, 0x75, 0x64, 0x22, 0x41, 0xf4, 0x41, 0xb8, 0x5d, 0x12, 0x13, 0x06, 0x8d,
	0x44, 0x70, 0xc5, 0xf1, 0xaa, 0xce, 0x69, 0x98, 0x9c, 0xc6, 0xef, 0x9c, 0xea, 0xf5, 0x1c, 0x14,
	0x84, 0xe0, 0x42, 0xba, 0xe6, 0x23, 0x45, 0x56, 0xd7, 0x72, 0x29, 0x51, 0xd8, 0x0d, 0x95, 0x6b,
	0x9e, 0x59, 0x86, 0x93, 0xcb, 0x50, 0x44, 0x1e, 0xba, 0xfa, 0x91, 0xfe, 0x5e, 0xfb, 0x88, 0x56,
	0xb6, 0x3b, 0xad, 0xa4, 0x09, 0x2c, 0x8c, 0xf7, 0x88, 0x3c, 0xf4, 0xe0, 0x6d, 0x0f, 0xa4, 0xc2,
	0x2f, 0x11, 0xee, 0x25, 0x11, 0x27, 0x6d, 0x9f, 0x07, 0x6f, 0x80, 0x2a, 0x5f, 0x63, 0xae, 0x96,
	0xd7, 0xca, 0xb7, 0xe7, 0x37, 0xd7, 0x1b, 0xb9, 0x86, 0x0d, 0x9f, 0xa6, 0x79, 0x61, 0x20, 0xcf,
	0x0c, 0x42, 0xb3, 0x3d, 0x29, 0x79, 0x4b, 0xbd, 0x5c, 0xac, 0x39, 0x87, 0x66, 0x44, 0x5a, 0xa5,
	0xf6, 0x14, 0xad, 0xe6, 0xaa, 0xcb, 0x84, 0xc7, 0x12, 0xf0, 0x26, 0x9a, 0x04, 0x21, 0xb2, 0x7a,
	0x6b, 0xf9, 0x7a, 0xa9, 0x12, 0xa6, 0xe2, 0x23, 0xbd, 0xf4, 0x74, 0x72, 0x6d, 0x0f, 0x61, 0x1d,
	0x79, 0x20, 0x0f, 0x87, 0xff, 0xc8, 0x7d, 0x84, 0x62, 0xde, 0x06, 0xdf, 0x88, 0x92, 0x11, 0x5e,
	0xcb, 0x13, 0xa6, 0x8a, 0x69, 0xf4, 0x8e, 0x5e, 0x79, 0x73, 0x1a, 0x62, 0x96, 0xb5, 0xef, 0x53,
	0xe8, 0x7f, 0x8b, 0xf6, 0xe2, 0x1d, 0x62, 0x1f, 0xad, 0x08, 0x48, 0xa2, 0x90, 0x12, 0x05, 0x7e,
	0x12, 0x02, 0x85, 0x54, 0xd6, 0x09, 0x43, 0x72, 0x67, 0xa4, 0xac, 0xde, 0x00, 0xf4, 0x5c, 0x63,
	0x32, 0x61, 0xb1, 0x28, 0x44, 0x71, 0x0b, 0x2d, 0x49, 0x20, 0x91, 0xb5, 0x67, 0x93, 0x86, 0xfc,
	0xd6, 0x48, 0xf2, 0x16, 0x90, 0xc8, 0xda, 0xb1, 0x45, 0x69, 0x45, 0xb4, 0x15, 0x04, 0x50, 0x08,
	0xfb, 0x56, 0xcf, 0x53, 0x67, 0x58, 0xc1, 0x4b, 0x21, 0xc3, 0x1d, 0x2f, 0x89, 0x5c, 0x0c, 0xef,
	0xa2, 0x45, 0x46, 0xad, 0x6e, 0xa7, 0x0d, 0xed, 0xcd, 0x91, 0xb4, 0xdb, 0x5b, 0x56, 0xaf, 0x0b,
	0x8c, 0x0e, 0x75, 0xfa, 0x0a, 0xad, 0x30, 0xea, 0x7f, 0xe0, 0xdd, 0x20, 0xb4, 0x7a, 0xad, 0x18,
	0xd2, 0x8d, 0x31, 0xa4, 0xfb, 0x06, 0x33, 0xdc, 0xec, 0x32, 0xa3, 0xb9, 0x20, 0xde, 0x46, 0x0b,
	0x8c, 0xfa, 0x5d, 0x50, 0x24, 0xa5, 0x9d, 0x31, 0xb4, 0x37, 0xc6, 0xd0, 0xee, 0x82, 0x22, 0x19,
	0x1f, 0x62, 0x74, 0xf0, 0xad, 0x89, 0xd0, 0xac, 0xc8, 0x7c, 0x54, 0xfb, 0x5c, 0x49, 0xcf, 0x80,
	0x07, 0x09, 0x17, 0xea, 0xef, 0x1c, 0xc1, 0x7f, 0xd4, 0x88, 0x45, 0xb7, 0x4c, 0x5d, 0x86, 0x5b,
	0xa6, 0x2f, 0xc7, 0x2d, 0x95, 0x0b, 0xba, 0x45, 0x6f, 0x56, 0x9b, 0xbf, 0x8b, 0x0b, 0x4e, 0x98,
	0x39, 0x63, 0xb3, 0x1e, 0x66, 0x20, 0x4b, 0x02, 0xdc, 0x2e, 0x44, 0x75, 0x01, 0x7a, 0x40, 0xa2,
	0x08, 0x62, 0x66, 0x09, 0x31, 0x7b, 0x46, 0x81, 0xad, 0x01, 0xc8, 0x72, 0x03, 0x2d, 0x44, 0x47,
	0xdc, 0x20, 0x73, 0x7f, 0xe0, 0x06, 0x19, 0x1e, 0x26, 0x3b, 0xe8, 0x4a, 0xfe, 0x20, 0x5d, 0xfc,
	0xae, 0xde, 0xfc, 0x36, 0x81, 0x96, 0x75, 0x68, 0xd7, 0x4c, 0xea, 0x16, 0x88, 0x7e, 0x48, 0x01,
	0x47, 0xe8, 0x3f, 0x6b, 0x60, 0xe1, 0x82, 0x3a, 0xe9, 0xf0, 0x6e, 0x9c, 0x36, 0x54, 0xab, 0x77,
	0xcf, 0x97, 0x9c, 0xdd, 0x0c, 0x25, 0xdc, 0x41, 0xf3, 0x43, 0xa3, 0x07, 0xaf, 0x8f, 0x81, 0xdb,
	0x53, 0xaf, 0xba, 0x71, 0x9e, 0xd4, 0x5f, 0x75, 0x38, 0x5a, 0xb4, 0x95, 0xc3, 0xe3, 0x3a, 0x2d,
	0xdc, 0x54, 0xd5, 0xfa, 0x39, 0xb3, 0x07, 0x05, 0x9b, 0xaf, 0xbf, 0x1c, 0x3b, 0xe5, 0xa3, 0x63,
	0xa7, 0xfc, 0xe3, 0xd8, 0x29, 0x7f, 0x3a, 0x71, 0x4a, 0x47, 0x27, 0x4e, 0xe9, 0xeb, 0x89, 0x53,
	0xda, 0x7f, 0xcc, 0x42, 0x75, 0xd0, 0x0b, 0x1a, 0x94, 0x77, 0xdd, 0x20, 0x0e, 0xea, 0xf4, 0x80,
	0x84, 0xb1, 0xcb, 0x04, 0x40, 0xdc, 0x09, 0x21, 0x6a, 0xd7, 0xa5, 0xe2, 0x82, 0x30, 0xa8, 0x27,
	0x82, 0xf7, 0xc3, 0x36, 0x08, 0xf7, 0xd4, 0x17, 0xac, 0xa0, 0x62, 0x5e, 0x6f, 0xee, 0xfd, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0xd4, 0xae, 0x02, 0x80, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GfSpManageServiceClient is the client API for GfSpManageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GfSpManageServiceClient interface {
	GfSpBeginTask(ctx context.Context, in *GfSpBeginTaskRequest, opts ...grpc.CallOption) (*GfSpBeginTaskResponse, error)
	GfSpAskTask(ctx context.Context, in *GfSpAskTaskRequest, opts ...grpc.CallOption) (*GfSpAskTaskResponse, error)
	GfSpReportTask(ctx context.Context, in *GfSpReportTaskRequest, opts ...grpc.CallOption) (*GfSpReportTaskResponse, error)
}

type gfSpManageServiceClient struct {
	cc grpc1.ClientConn
}

func NewGfSpManageServiceClient(cc grpc1.ClientConn) GfSpManageServiceClient {
	return &gfSpManageServiceClient{cc}
}

func (c *gfSpManageServiceClient) GfSpBeginTask(ctx context.Context, in *GfSpBeginTaskRequest, opts ...grpc.CallOption) (*GfSpBeginTaskResponse, error) {
	out := new(GfSpBeginTaskResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpManageService/GfSpBeginTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gfSpManageServiceClient) GfSpAskTask(ctx context.Context, in *GfSpAskTaskRequest, opts ...grpc.CallOption) (*GfSpAskTaskResponse, error) {
	out := new(GfSpAskTaskResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpManageService/GfSpAskTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gfSpManageServiceClient) GfSpReportTask(ctx context.Context, in *GfSpReportTaskRequest, opts ...grpc.CallOption) (*GfSpReportTaskResponse, error) {
	out := new(GfSpReportTaskResponse)
	err := c.cc.Invoke(ctx, "/base.types.gfspserver.GfSpManageService/GfSpReportTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GfSpManageServiceServer is the server API for GfSpManageService service.
type GfSpManageServiceServer interface {
	GfSpBeginTask(context.Context, *GfSpBeginTaskRequest) (*GfSpBeginTaskResponse, error)
	GfSpAskTask(context.Context, *GfSpAskTaskRequest) (*GfSpAskTaskResponse, error)
	GfSpReportTask(context.Context, *GfSpReportTaskRequest) (*GfSpReportTaskResponse, error)
}

// UnimplementedGfSpManageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGfSpManageServiceServer struct {
}

func (*UnimplementedGfSpManageServiceServer) GfSpBeginTask(ctx context.Context, req *GfSpBeginTaskRequest) (*GfSpBeginTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpBeginTask not implemented")
}
func (*UnimplementedGfSpManageServiceServer) GfSpAskTask(ctx context.Context, req *GfSpAskTaskRequest) (*GfSpAskTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpAskTask not implemented")
}
func (*UnimplementedGfSpManageServiceServer) GfSpReportTask(ctx context.Context, req *GfSpReportTaskRequest) (*GfSpReportTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GfSpReportTask not implemented")
}

func RegisterGfSpManageServiceServer(s grpc1.Server, srv GfSpManageServiceServer) {
	s.RegisterService(&_GfSpManageService_serviceDesc, srv)
}

func _GfSpManageService_GfSpBeginTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpBeginTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpManageServiceServer).GfSpBeginTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpManageService/GfSpBeginTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpManageServiceServer).GfSpBeginTask(ctx, req.(*GfSpBeginTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GfSpManageService_GfSpAskTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpAskTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpManageServiceServer).GfSpAskTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpManageService/GfSpAskTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpManageServiceServer).GfSpAskTask(ctx, req.(*GfSpAskTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GfSpManageService_GfSpReportTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GfSpReportTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GfSpManageServiceServer).GfSpReportTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/base.types.gfspserver.GfSpManageService/GfSpReportTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GfSpManageServiceServer).GfSpReportTask(ctx, req.(*GfSpReportTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GfSpManageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "base.types.gfspserver.GfSpManageService",
	HandlerType: (*GfSpManageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GfSpBeginTask",
			Handler:    _GfSpManageService_GfSpBeginTask_Handler,
		},
		{
			MethodName: "GfSpAskTask",
			Handler:    _GfSpManageService_GfSpAskTask_Handler,
		},
		{
			MethodName: "GfSpReportTask",
			Handler:    _GfSpManageService_GfSpReportTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/types/gfspserver/manage.proto",
}

func (m *GfSpBeginTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpBeginTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpBeginTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Request != nil {
		{
			size := m.Request.Size()
			i -= size
			if _, err := m.Request.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GfSpBeginTaskRequest_UploadObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpBeginTaskRequest_UploadObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UploadObjectTask != nil {
		{
			size, err := m.UploadObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *GfSpBeginTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpBeginTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpBeginTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpAskTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpAskTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NodeLimit != nil {
		{
			size, err := m.NodeLimit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpAskTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpAskTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Response != nil {
		{
			size := m.Response.Size()
			i -= size
			if _, err := m.Response.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GfSpAskTaskResponse_ReplicatePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_ReplicatePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ReplicatePieceTask != nil {
		{
			size, err := m.ReplicatePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *GfSpAskTaskResponse_SealObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_SealObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SealObjectTask != nil {
		{
			size, err := m.SealObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpAskTaskResponse_ReceivePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_ReceivePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ReceivePieceTask != nil {
		{
			size, err := m.ReceivePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *GfSpAskTaskResponse_GcObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_GcObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcObjectTask != nil {
		{
			size, err := m.GcObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpAskTaskResponse_GcZombiePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_GcZombiePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcZombiePieceTask != nil {
		{
			size, err := m.GcZombiePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *GfSpAskTaskResponse_GcMetaTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpAskTaskResponse_GcMetaTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcMetaTask != nil {
		{
			size, err := m.GcMetaTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpReportTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Request != nil {
		{
			size := m.Request.Size()
			i -= size
			if _, err := m.Request.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GfSpReportTaskRequest_UploadObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_UploadObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.UploadObjectTask != nil {
		{
			size, err := m.UploadObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_ReplicatePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_ReplicatePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ReplicatePieceTask != nil {
		{
			size, err := m.ReplicatePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_SealObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_SealObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SealObjectTask != nil {
		{
			size, err := m.SealObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_GcObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_GcObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcObjectTask != nil {
		{
			size, err := m.GcObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_GcZombiePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_GcZombiePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcZombiePieceTask != nil {
		{
			size, err := m.GcZombiePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_GcMetaTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_GcMetaTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GcMetaTask != nil {
		{
			size, err := m.GcMetaTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_DownloadObjectTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_DownloadObjectTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DownloadObjectTask != nil {
		{
			size, err := m.DownloadObjectTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_ChallengePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_ChallengePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ChallengePieceTask != nil {
		{
			size, err := m.ChallengePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskRequest_ReceivePieceTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskRequest_ReceivePieceTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.ReceivePieceTask != nil {
		{
			size, err := m.ReceivePieceTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	return len(dAtA) - i, nil
}
func (m *GfSpReportTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GfSpReportTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GfSpReportTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintManage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintManage(dAtA []byte, offset int, v uint64) int {
	offset -= sovManage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GfSpBeginTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		n += m.Request.Size()
	}
	return n
}

func (m *GfSpBeginTaskRequest_UploadObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UploadObjectTask != nil {
		l = m.UploadObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpBeginTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}

func (m *GfSpAskTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeLimit != nil {
		l = m.NodeLimit.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}

func (m *GfSpAskTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	if m.Response != nil {
		n += m.Response.Size()
	}
	return n
}

func (m *GfSpAskTaskResponse_ReplicatePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReplicatePieceTask != nil {
		l = m.ReplicatePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpAskTaskResponse_SealObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SealObjectTask != nil {
		l = m.SealObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpAskTaskResponse_ReceivePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReceivePieceTask != nil {
		l = m.ReceivePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpAskTaskResponse_GcObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcObjectTask != nil {
		l = m.GcObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpAskTaskResponse_GcZombiePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcZombiePieceTask != nil {
		l = m.GcZombiePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpAskTaskResponse_GcMetaTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcMetaTask != nil {
		l = m.GcMetaTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		n += m.Request.Size()
	}
	return n
}

func (m *GfSpReportTaskRequest_UploadObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UploadObjectTask != nil {
		l = m.UploadObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_ReplicatePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReplicatePieceTask != nil {
		l = m.ReplicatePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_SealObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SealObjectTask != nil {
		l = m.SealObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_GcObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcObjectTask != nil {
		l = m.GcObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_GcZombiePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcZombiePieceTask != nil {
		l = m.GcZombiePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_GcMetaTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GcMetaTask != nil {
		l = m.GcMetaTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_DownloadObjectTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DownloadObjectTask != nil {
		l = m.DownloadObjectTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_ChallengePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChallengePieceTask != nil {
		l = m.ChallengePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskRequest_ReceivePieceTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReceivePieceTask != nil {
		l = m.ReceivePieceTask.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}
func (m *GfSpReportTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovManage(uint64(l))
	}
	return n
}

func sovManage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozManage(x uint64) (n int) {
	return sovManage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GfSpBeginTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpBeginTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpBeginTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpUploadObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpBeginTaskRequest_UploadObjectTask{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpBeginTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpBeginTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpBeginTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpAskTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpAskTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpAskTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeLimit == nil {
				m.NodeLimit = &gfsplimit.GfSpLimit{}
			}
			if err := m.NodeLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpAskTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpAskTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpAskTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicatePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpReplicatePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_ReplicatePieceTask{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SealObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpSealObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_SealObjectTask{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpReceivePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_ReceivePieceTask{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_GcObjectTask{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcZombiePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCZombiePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_GcZombiePieceTask{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcMetaTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCMetaTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Response = &GfSpAskTaskResponse_GcMetaTask{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpReportTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpReportTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpReportTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpUploadObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_UploadObjectTask{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicatePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpReplicatePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_ReplicatePieceTask{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SealObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpSealObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_SealObjectTask{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_GcObjectTask{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcZombiePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCZombiePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_GcZombiePieceTask{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GcMetaTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpGCMetaTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_GcMetaTask{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DownloadObjectTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpDownloadObjectTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_DownloadObjectTask{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpChallengePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_ChallengePieceTask{v}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivePieceTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &gfsptask.GfSpReceivePieceTask{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Request = &GfSpReportTaskRequest_ReceivePieceTask{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GfSpReportTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowManage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GfSpReportTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GfSpReportTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowManage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthManage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthManage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &gfsperrors.GfSpError{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipManage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthManage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipManage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowManage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowManage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowManage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthManage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupManage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthManage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthManage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowManage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupManage = fmt.Errorf("proto: unexpected end of group")
)
